### ISSUE TITLE
PUT method

### ISSUE THREAD

**Issue by mk0y** [Vertrical/tino#1]
PUT method for jsondb responder.

```js
PUT /api/laptops/1
{
  brand: "..."
  other: "props",
  ...
}
```

If the record doesn't exist create it, otherwise replace it. 

Same as with POST method in https://github.com/Vertrical/json_server/issues/3 it should accept all possible values too.

**Comment by mk0y** [comment]
I'm sending PUT to `http PUT :8000/api/laptops/123 brand=hp name=HP`

And getting: 

```js
HTTP/1.1 200 OK
content-length: 203
content-type: application/json

{
    "response": {
        "color": {
            "dark": "blue",
            "light": "red"
        },
        "genres": [
            "comedy",
            "thriller",
            "drama"
        ],
        "laptops": [
            {
                "brand": "dell",
                "id": 123
            },
            {
                "brand": "lenovo",
                "id": 2321
            },
            {
                "brand": "toshiba",
                "id": 3311
            },
            {
                "brand": "hp",
                "name": "HP"
            }
        ]
    }
}
```

It should replace laptop with ID=123.

**Comment by panther99** [comment]
I think it's because `view` does search only by the index. It should either be refactored or there should be another way to fetch items (this is error prone also, for example if user tries to access `/laptops/5`, we're not sure if it's laptop on the index 5 or with the ID 5).

**Comment by mk0y** [comment]
Then `tryDirectLens` and `tryRestful` should switch places maybe?
